<!DOCTYPE html><?php include("{$gl_path_to_root}codesfragms/ban"); ?>	
<!-- saved from url=(0029)http://www.ministrybooks.org/ -->
<html class=" js no-touch svg inlinesvg svgclippaths no-ie8compat" lang="en"><!--<![endif]-->
  <head>
    <!-- Google Tag Manager (noscript) ТОЛЬКО ДЛЯ САЙТА .online
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-NSB4TV33"
    height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>-->
    <!-- End Google Tag Manager (noscript) -->
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Google Tag Manager 
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
      new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
      j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
      'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-NSB4TV33');</script>-->
    <!-- End Google Tag Manager -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    
  	 <?php setmeta($gl_page, $site_keywords, $site_descr)?>
  	<title><?php print $site_title; ?></title>
   
    <!-- stylesheets -->
	<link rel="stylesheet" href="themes/general/index/foundation.min.css">
    <link rel="stylesheet" href="themes/general/index/app.css">    
    <!-- Google Fonts -->
    <link href="themes/general/index/css" rel="stylesheet" type="text/css">
    <!-- javascript -->
  	<script type="text/javascript" async src="themes/general/index/ga.js"></script><script src="themes/general/index/custom.modernizr.js"></script>
  	<script src="themes/general/index/jquery.min.js"></script>
    <script src="themes/general/index/scroll-top.js"></script>
    <!-- Google Analytics -->
  	<script type="text/javascript">		
      var _gaq = _gaq || [];
  		    _gaq.push(['_setAccount', 'UA-15609289-1']);
    	    _gaq.push(['_trackPageview']);

  		(function() {
    		var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    		ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    		var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  		})();
  	</script>
</head>
<body id="top" style="padding-top: 0px;">

<div id="header">
  <div class="row">
          <div class="large-12 columns">
               <a href="http://www.ministrybooks.org/"><img src="themes/general/index/lsm-logo.png" alt="Living Stream Ministry logo" class="logo"></a>
               <h1>Living Stream Ministry</h1>
               <h2>Publisher of Watchman Nee &amp; Witness Lee</h2>
          </div>
    </div>
    <div class="row">
          <div class="large-12 columns spanish-link">
          	<a href="http://www.librosdelministerio.org/">Publicaciones en linea en espanol</a>
          </div>
    </div>
</div> 

<div class="contain-to-grid sticky">
  <nav class="top-bar">
    <ul class="title-area">
      <li class="name"></li>
      <li class="toggle-topbar menu-icon"><a href="http://www.ministrybooks.org/#"><span>Online Publications Menu</span></a></li>
    </ul>
    
  <section class="top-bar-section" style="left: 0%;">
      <ul class="left">
        <li><a href="http://www.ministrybooks.org/index.cfm">Home</a></li>
        <li><a href="http://www.ministrybooks.org/alphabetical.cfm">Books A-Z</a></li>
        <li><a href="http://www.ministrybooks.org/categories.cfm">Books by Category</a></li>
        <li><a href="http://www.ministrybooks.org/watchman-nee-books.cfm">Books by Watchman Nee</a></li>
        <li class="has-dropdown not-click"><a href="http://www.ministrybooks.org/witness-lee-books.cfm">Books by Witness Lee</a>
          <ul class="dropdown"><li class="title back js-generated"><h5><a href="http://www.ministrybooks.org/#">« Back</a></h5></li><li><a class="parent-link js-generated" href="http://www.ministrybooks.org/witness-lee-books.cfm">Books by Witness Lee</a></li>
            <li><a href="http://www.ministrybooks.org/life-studies.cfm">Life-Study of the Bible</a></li>
            <li><a href="http://www.ministrybooks.org/conclusion.cfm">Conclusion of the New Testament</a></li>
            <li><a href="http://www.ministrybooks.org/high-peak.cfm">High Peak Books</a></li>
          </ul>
        </li>
        <li class="has-dropdown not-click"><a href="http://www.ministrybooks.org/lsm-websites.cfm">Other LSM Websites</a>
          <ul class="dropdown"><li class="title back js-generated"><h5><a href="http://www.ministrybooks.org/#">« Back</a></h5></li><li><a class="parent-link js-generated" href="http://www.ministrybooks.org/lsm-websites.cfm">Other LSM Websites</a></li>
            <li><a href="http://www.lsm.org/">About LSM</a></li>
            <li><a href="https://www.livingstream.com/">Online Bookstore</a></li>
            <li><a href="http://www.recoveryversion.org/">The Recovery Version of the Bible</a></li>
            <li><a href="http://www.lsmradio.com/">Life-Study of the Bible Radio Broadcast</a></li>
            <li><a href="http://www.affcrit.com/">Affirmation &amp; Critique</a></li>
            <li><a href="http://www.emanna.com/">eManna</a></li>
            <li><a href="http://www.lsmwebcast.com/">Webcast Subscription Service</a></li>
          </ul>
        </li>
        <li><a href="http://www.ministrybooks.org/SearchMinBooks.cfm" title="Search Online Publications">Search <span aria-hidden="true" data-icon="?"></span> </a></li>
      </ul>
    </section></nav>
</div>


<div class="row">
  <div class="large-12 columns">
    <img src="themes/general/index/read-search-banner.jpg" width="900" height="170" alt="Read and Search the Ministry of Watchman Nee and Witness Lee" title="Read and Search the Ministry of Watchman Nee and Witness Lee" class="banner-img">
    
    
    
    <h2 class="site-title">Online Publications from Living Stream Ministry</h2>
    <?php include("{$gl_path_to_engine}public/content.inc"); ?>
      </div>
</div>

<div class="row">
  <div class="large-12 columns">
    <div id="notice">
           
    </div>
    
      <div class="panel">
        <h3>Search Online Publications</h3>
        <form action="http://www.ministrybooks.org/SearchMinBooks.cfm" method="post">
          <div class="row">
            <div class="large-12 columns">
              <div class="row collapse">
                <div class="small-9 columns">
                  <input type="text" name="srcstr" value="">
                </div>
                <div class="small-3 columns">
                  <input class="button prefix" type="submit" name="search" value="Search">
                </div>
                <p class="small-note">Simply enter a word or phrase. Common words, such as "and", "is", and "the", also known as <a href="http://www.ministrybooks.org/#" data-reveal-id="myModalNoise">noise words</a>, are bypassed in a search.</p>
                <p class="text-right"><a href="http://www.ministrybooks.org/SearchMinBooks.cfm">Advanced Search</a></p>
              </div>
            </div>
          </div>
          <input type="hidden" name="stype" value="F">
          <input type="hidden" name="bypub" value="ALL">
        </form>
      </div>
    

  </div>
</div>

<div id="footer-links">
	<div class="row">
    <div class="large-12 columns">
      <div class="row">
       	<div class="large-5 columns">
         	<h4>Other Reading Online</h4>
          <ul class="vertical">
            <li><a href="http://www.ministrysamples.org/">Read and Share Ministry Excerpts</a></li>
            <li><a href="http://www.ministrybooks.org/reading">Create a Scheduled Reading Plan</a></li>
            <li><a href="http://www.lsm.org/epublications.html">Electronic Publications (Kindle, EPUB, iSilo)</a></li>
            <li><a href="http://online.recoveryversion.org/">Online Recovery Version</a></li>
            <li><a href="http://www.librosdelministerio.org/">Publicaciones en linea en espanol</a></li>
          </ul>
       	</div>
      	<div class="large-7 columns">
        	<h4>About Living Stream Ministry</h4>
        	<p>Living Stream Ministry publishes the works of Watchman Nee and Witness Lee, providing the authoritative and definitive collections of treasures from these two servants of the Lord Jesus Christ. The writings of Watchman Nee and Witness Lee focus on the enjoyment of the divine life, which all the believers possess, and on the building up of the church, the goal of God's work with man in this age.</p>	
        </div>
      </div>
    </div>
  </div>
    
  <div class="row">
    <div class="large-12 columns">
      <ul class="button-group">
        <li><a href="http://www.ministrybooks.org/index.cfm" class="button tiny secondary radius">Home</a></li>
        <li><a href="http://www.ministrybooks.org/alphabetical.cfm" class="button tiny secondary radius">Books A-Z</a></li>
        <li><a href="http://www.ministrybooks.org/categories.cfm" class="button tiny secondary radius">Books by Category</a></li>
        <li><a href="http://www.ministrybooks.org/watchman-nee-books.cfm" class="button tiny secondary radius">Books by Watchman Nee</a></li>
        <li><a href="http://www.ministrybooks.org/witness-lee-books.cfm" class="button tiny secondary radius">Books by Witness Lee</a></li>
        <li><a href="http://www.ministrybooks.org/lsm-websites.cfm" class="button tiny secondary radius">Other LSM Websites</a></li>
        <li><a href="http://www.ministrybooks.org/SearchMinBooks.cfm" class="button tiny secondary radius">Search</a></li>
        <li><a href="http://www.ministrybooks.org/watchman-nee-witness-lee-book-tocs.cfm" class="button tiny secondary radius">View Tables of Contents</a></li>
      </ul>
    </div>
  </div>
</div>

<div id="footer">
	<div class="row">
   	<div class="large-9 columns">
      <p>© 2016 Living Stream Ministry. All rights reserved. Reproduction in whole or in part without permission is prohibited.</p>
    </div>
    <div class="large-3 columns">
     	<p class="right"><a href="mailto:webmaster@lsm.org">Contact Us</a> | <a href="http://www.ministrybooks.org/sitemap.cfm">Sitemap</a> | <a href="http://www.ministrybooks.org/copyright-policy.cfm">Copyright Policy</a></p>
    </div>
  </div>
</div>

<!-- Modals -->
<div id="myModalNoise" class="reveal-modal">
 	<h2>Noise Words</h2>
 	<p>Common words, such as "and", "is", "but", and "the", also known as noise words, are bypassed in a search. The search string, the Spirit &amp; who, would result in an error since who, which stands by itself, is a noise word. The following is a list of noise words:</p>
	<p>$, a, also, an, and, another, any, are, as, at, be, because, been, being, both, but, by, came, can, did, do, each, for, has, had, he, have, her, here, him, himself, his, how, if, in, into, is, it, like, make, me, might, much, my, of, on, or, our, out, over, said, should, since, some, still, such, take, than, that, the, their, them, then, there, these, they, this, those, to, too, very, was, way, we, well, were, what, where, which, while, who, with, would, you, your</p>
 	<a class="close-reveal-modal">?</a>
</div>

<div id="myModalRanking" class="reveal-modal">
  	<h2>Ranking</h2>
  	<p>Rank is a value from <strong>0</strong> to <strong>1000</strong> indicating how closely a match scored or ranked against the original search string. Rank values are affected by the following factors:</p>
		<ol>
            <li><span>The total number of occurrences of the original search words/phrases in a portion of a book.</span></li>
            <li><span>Content that includes the search words in close proximity to each other are ranked above those that do not. Therefore, a portion of a book that has the search words in close proximity may have a higher ranking than another portion of a book that has a higher hit count but the words are not in close proximity to one another. Therefore, we also include a search word hit count for reference.</span></li>
            <li><span>The rank values are relative to each other. Therefore, it is not possible to interpret the RANK value as a percentage or group the rank values into high/medium/low ranges. Think of rank as a method to order the results for a specific search.</span></li>
        </ol>
  	<a class="close-reveal-modal">?</a>
</div>

<div id="myModalScope" class="reveal-modal">
 	<h2>Search Scope</h2>
 	<h3>Include All Word Forms</h3>
	<p>This option breaks out the search string into its individual words and generates all conjugations and declensions for each word in the search phrase. A search on the word, dwell, would search for dwell, dwelling, dwelling's, dwells, dwelt, and dwelled.</p>
	<p>There is no need to use ^ (inflectional search) or * (prefix search) when using the Include all word forms search scope.</p> 
	<h3>Specified Word Forms</h3>
	<p>This option searches for exact matches of the specified words or phrases used in the search string. Use of ^ (inflectional search) with a particular word in the search string will broaden the search for that given word in that all conjugations and declensions for that word will be searched. Similarly, use of * (prefix search) with a particular word in the search string will broaden the search for that given word in that all words with that prefix will be searched as well.</p> 
	<h3>Note</h3>
	<p>Common words, such as "and", "is", "but", and "the", also known as noise words, are bypassed in a search. A list of all noise words is as follows:</p>
	<p>$, about, after, all, also, an,and, another, any, are, as, at, be, because, been, before, being, between, both, but, by, came, can, come, could, did, do, each, for, from, get, got, has, had, he, have, her, here, him, himself, his, how, if, in, into, is, it, like, make, many, me, might, more, most, much, must, my, never, now, of, on, only, or, other, our, out, over, said, same, see, should, since, some, still, such, take, than, that, the, their, them, then, there, these, they, this, those, through, to, too, under, up, very, was, way, we, well, were, what, where, which, while, who, with, would, you, your</p>
  	<a class="close-reveal-modal">?</a>
</div>

<script>
  document.write('<script src=' +
   ('__proto__' in {} ? 'js/vendor/zepto' : 'js/vendor/jquery') +
   '.js><\/script>')
</script><script src="themes/general/index/zepto.js"></script>

<script src="themes/general/index/foundation.min.js"></script>
<script>
	$(document).foundation();
</script>
<script src="themes/general/index/ios-orientationchange-fix.js"></script>
  



</body></html>