<?php
//_articles_edit.inc
  //captions
  $l_s_articles[1] = "Заголовок";
  $l_s_articles[2] = "Краткое описание";
  $l_s_articles[3] = "Позиция";
  $l_s_articles[4] = "Картинка";
  $l_s_articles[5] = "Дата";
//s_articles_add.inc
  //h1
  $l_s_articles[6] = "Добавить статью";
  $l_s_articles[7] = "Параметры статьи";
  //errors
  $l_s_articles[8]  = "Заполните, пожалуйста, поле <b>заголовок</b>.";
  $l_s_articles[9]  = "Введите целое положительное число в поле <b>позиция</b>.";
//s_articles_del.inc
  $l_s_articles[10] = "Хотите удалить эту статью?";
//s_articles_settings.inc
  $l_s_articles[11] = "Статьи :: настройки";
  $l_s_articles[12] = "Шаблон сайта";
  $l_s_articles[13] = "Статей на страницу";
  $l_s_articles[14] = "Заголовок";
  $l_s_articles[15] = "Вернуться в список статей";
//s_articles_list
  //menu
  $l_s_articles[16] = "Добавить статью";
  $l_s_articles[17] = "Настройки";
  //info
  $l_s_articles[18] = "Этот раздел пока находится в стадии разработки.";
  $l_s_articles[19] = "текст";
  //options
  $l_s_articles[20] = "параметры";
  $l_s_articles[21] = "удалить";
  $l_s_articles[22] = "подробнее";
//s_articles_text
  $l_s_articles[23] = "Статья";
  $l_s_articles[24] = "Посмотреть статью";
  $l_s_articles[25] = "Вернуться в список статей";
  $l_s_articles[26] = "<h1>Информация</h1><p>Данная страница находится в стадии разработки.</p>";
//pub_seacrh
  $l_s_articles[27] = "Количество найденных элементов";
  $l_s_articles[28] = "Поиск не дал результатов.";
  $l_s_articles[29] = "Статьи";

  $l_s_articles[30] = "нет (основной шаблон)";

?>