<?php

  //////////////////////////////////////////////////////////////////////////////
  //Справочник url-адресов ?adm=url_list
  //////////////////////////////////////////////////////////////////////////////


  print "<h1>{$l_url[3]}</h1>";
  print "<h2>{$l_url[4]}</h2>";

  print "<h3>{$l_url[5]}</h3>";
  print "<p>";
  print "<b>{$l_url[1]}</b>: <a href='?adm=bbd_auth' target='_blank'>?adm=bbd_auth</a><br>";
  print "<b>{$l_url[2]}</b>:  <a href='{$gl_site}?adm=bbd_auth' target='_blank'>{$gl_site}?adm=bbd_auth</a><br>";
  print "</p>";

  print "<h3>{$l_url[6]}</h3>";
  print "<p>";
  print "<b>{$l_url[1]}</b>: <a href='?adm=users_add' target='_blank'>?adm=users_add</a><br>";
  print "<b>{$l_url[2]}</b>:  <a href='{$gl_site}?adm=users_add' target='_blank'>{$gl_site}?adm=users_add</a><br>";
  print "</p>";

  print "<h3>{$l_url[7]}</h3>";
  print "<p>";
  print "<b>{$l_url[1]}</b>: <a href='?adm=users_edit' target='_blank'>?mod=users_edit</a><br>";
  print "<b>{$l_url[2]}</b>:  <a href='{$gl_site}?adm=users_edit' target='_blank'>{$gl_site}?adm=users_edit</a><br>";
  print "</p>";

  print "<h3>{$l_url[8]}</h3>";
  print "<p>";
  print "<b>{$l_url[1]}</b>: <a href='?mod=users_chpsw_pub' target='_blank'>?mod=users_chpsw_pub</a><br>";
  print "<b>{$l_url[2]}</b>:  <a href='{$gl_site}?mod=users_chpsw_pub' target='_blank'>{$gl_site}?mod=users_chpsw_pub</a><br>";
  print "</p>";

  print "<h3>{$l_url[9]}</h3>";
  print "<p>";
  print "<b>{$l_url[1]}</b>: <a href='?mod=users_list_pub' target='_blank'>?mod=users_list_pub</a><br>";
  print "<b>{$l_url[2]}</b>:  <a href='{$gl_site}?mod=users_list_pub' target='_blank'>{$gl_site}?mod=users_list_pub</a><br>";
  print "</p>";

  print "<h3>{$l_url[10]}</h3>";
  print "<p>";
  print "<b>{$l_url[1]}</b>: <a href='?act=auth_exit' target='_blank'>?act=auth_exit</a><br>";
  print "<b>{$l_url[2]}</b>:  <a href='{$gl_site}?act=auth_exit' target='_blank'>{$gl_site}?act=auth_exit</a><br>";
  print "</p>";
  print "<br>";

  print "<h2>{$l_url[11]}</h2>";
  print "<h3>{$l_url[12]}</h3>";
  print "<p>";
  print "<b>{$l_url[1]}</b>: <a href='?mod=search' target='_blank'>?mod=search</a><br>";
  print "<b>{$l_url[2]}</b>:  <a href='{$gl_site}?mod=search' target='_blank'>{$gl_site}?mod=search</a><br>";
  print "</p>";

  print "<h3>{$l_url[13]}</h3>";
  print "<p>";
  print "<b>{$l_url[1]}</b>: <a href='?mod=search_tips' target='_blank'>?mod=search_tips</a><br>";
  print "<b>{$l_url[2]}</b>:  <a href='{$gl_site}?mod=search_tips' target='_blank'>{$gl_site}?mod=search_tips</a><br>";
  print "</p>";
  print "<br>";

  print "<h2>{$l_url[14]}</h2>";

  print "<h3>{$l_url[15]}</h3>";
  print "<p>";
  print "<b>{$l_url[1]}</b>: <a href='?mod=sitemap' target='_blank'>?mod=sitemap</a><br>";
  print "<b>{$l_url[2]}</b>:  <a href='{$gl_site}?mod=sitemap' target='_blank'>{$gl_site}?mod=sitemap</a><br>";
  print "</p>";
  print "<br>";

  print "<h2>{$l_url[16]}</h2>";
  print "<p>";
  print "<b>{$l_url[1]}</b>: <a href='?adm=main' target='_blank'>?adm=main</a><br>";
  print "<b>{$l_url[2]}</b>:  <a href='{$gl_site}?adm=main' target='_blank'>{$gl_site}?adm=main</a><br>";
  print "</p><br><br><br><br><br><br><br><br>";
?>