<?php
//references
  $l_adm_gen[1] = "Вернуться в главное меню";
//buttons
  $l_adm_gen[2] = "Сохранить";
  $l_adm_gen[3] = "Подтвердить";
  $l_adm_gen[4] = "Назад";
  $l_adm_gen[5] = "ДА";
  $l_adm_gen[6] = "НЕТ";

//references
  $l_adm_gen[10] = "Назад";
  $l_adm_gen[11] = "Вернуться";
//info
  $l_adm_gen[20] = "Информация";

//page title
  $l_adm_gen[21] = "CMS Коллектор библейской книги :: система администрирования";  
?>