<?php
//regform_fields_list.inc
  $l_regform_fields[1] = "Поля формы регистрации";
  //form select options
  $l_regform_fields[2] = "Поле ввода (text)";
  $l_regform_fields[3] = "Многострочное поле ввода (textarea)";
  $l_regform_fields[4] = "Флажок (checkbox)";
  $l_regform_fields[5] = "Radio-кнопки";
  $l_regform_fields[6] = "Список выбора (select)";
  $l_regform_fields[7] = "Заголовок группы полей";
  //button
  $l_regform_fields[8] = "Добавить";


//_fields_edit.inc
  $l_regform_fields[10]  = "Опции поля";
  $l_regform_fields[11]  = "Имя поля (допустимые символы: a-z, 0-9, _)";
  $l_regform_fields[12]  = "Название поля (подпись)";
  $l_regform_fields[13]  = "Обязательное";
  $l_regform_fields[14] = "Позиция";
  $l_regform_fields[15] = "Свойства text";
  $l_regform_fields[16] = "Значение по умолчанию";
  $l_regform_fields[17] = "Свойства textarea";
  $l_regform_fields[18] = "Значение по умолчанию";
  $l_regform_fields[19] = "Количество строк";
  $l_regform_fields[20] = "да";
  $l_regform_fields[21] = "нет";
  $l_regform_fields[22] = "Свойства checkbox";
  $l_regform_fields[23] = "Положительный ответ";
  $l_regform_fields[24] = "Отрицательный ответ";
  $l_regform_fields[25] = "Отмечен";
  $l_regform_fields[26] = "Свойства radio";
  $l_regform_fields[27] = "Опции (резделитель&nbsp;-&nbsp;;&nbsp;)";
  $l_regform_fields[28] = "Свойства select";
  $l_regform_fields[29] = "Опции (резделитель&nbsp;-&nbsp;;&nbsp;)";
  $l_regform_fields[30] = "Высота списка (количество строк)";
  $l_regform_fields[31] = "Множественный выбор";

  //h1
  $l_regform_fields[33] = "Добавить поле";


//regform_fields_add.inc regform_fields_edit.inc
  //errors
  $l_regform_fields[34] = "Заполните, пожалуйста, поле <b>Название поля (подпись)</b>.";
  $l_regform_fields[35] = "Введите целое положительное число в поле <b>позиция</b>.";
  $l_regform_fields[36] = "Недопустимые символы в поле <b>имя поля</b>";
  $l_regform_fields[37] = "Запрещенное имя поля";
  $l_regform_fields[38] = "Поле <b>{field_name}</b> уже есть в этой форме.";
  $l_regform_fields[39] = "Введите целое положительное число в поле <b>количество строк</b>.";
  $l_regform_fields[40] = "Заполните, пожалуйста, поле <b>положительный ответ</b>.";
  $l_regform_fields[41] = "Заполните, пожалуйста, поле <b>отрицательный ответ</b>.";
  $l_regform_fields[42] = "Введите целое положительное число в поле <b>высота списка</b>.";
  $l_regform_fields[43] = "Заполните, пожалуйста, поле <b>опции</b>.";
  $l_regform_fields[44] = "Заполните, пожалуйста, поле <b>опции</b>.";
//regform_fields_list.inc
  $l_regform_fields[45] = "поле";
  $l_regform_fields[46] = "тип";
  $l_regform_fields[47] = "обязательное";
  $l_regform_fields[48] = "опции";
  $l_regform_fields[49] = "параметры";
  $l_regform_fields[50] = "удалить";
  $l_regform_fields[51] = "Не добавлено ни одного поля.";

//regform_fields_del.inc
  $l_regform_fields[52] = "Хотите удалить это поле?";

//regform_fields_list.inc
  $l_regform_fields[53] = "Тип поля";

//regform_fields_edit.inc
  $l_regform_fields[54] = "Параметры поля";
  $l_regform_fields[55] = "Показывать в списке пользователей";
  $l_regform_fields[56] = "";
  $l_regform_fields[57] = "";




  $l_regform_fields[1000] = "Вернуться в список полей";
?>