<?php 
$l_menu[1] = "выйти"; 
$l_menu[2] = "войти"; 
$l_menu[3] = "Регистрация"; 
$l_menu[4] = "Главы:"; 
$l_menu[5] = "Содержание"; 
$l_menu[6] = "<div style='color: #000; font-size: 12px; font-family: Arial, Verdana; padding:10px; width:200px; line-height:120%'>Чтобы заказать печатный вариант книги, обратитесь к нашему каталогу на сайте <a class='chap' href='http://kbk.ru/catalog/download/'>«Коллектора библейской книги»</a></div>"; 
$l_menu[7] = "class='chap'";
$l_menu[8] = "<div style='color: #000000; font-size: 12px; font-family: Verdana, Arial, Helvetica, sans-serif; padding:10px;'>";
$l_menu[9] = "<div style='color: #000000; font-size: 12px; font-weight:normal; font-family: Arial, Verdana;line-height:120%; padding:10px; padding-right:0px; text-align:left;width:205px;'>";
?>