<?php
  $l_usregform[1]  = "Имя";
  $l_usregform[2]  = "Логин";
  $l_usregform[3]  = "Пароль";
  $l_usregform[4]  = "Подтвердите пароль";
  $l_usregform[5]  = "E-mail";
  $l_usregform[6]  = "Телефон";
  $l_usregform[7]  = "Сайт";
  $l_usregform[8]  = "ICQ";
  $l_usregform[9]  = "Город";
  $l_usregform[10] = "Организация";
  $l_usregform[11] = "Доп. информация";
  $l_usregform[12] = "Введите код";
  $l_usregform[13] = "Код";


  $l_usregform[14] = "Получать сообщения администрации";
  $l_usregform[15] = "";
  $l_usregform[16] = "";
  $l_usregform[17] = "";
  $l_usregform[18] = "";
  $l_usregform[19] = "";
  $l_usregform[20] = "";
?>