<?php
  //auth.inc
  $l_auth[1] = "Неверный логин или пароль.";
  $l_auth[2] = "Вернуться назад";
  //auth_form.inc
  $l_auth[3] = "Логин";
  $l_auth[4] = "Пароль";
  $l_auth[5] = "Запомнить пароль";
  $l_auth[6] = "Войти";
//auth_succ
  //h1
  $l_auth[7] = "Авторизация";
  //messages
  $l_auth[8]  = "<div class='user_icon'>Здравствуйте, <b>{name}</b>, авторизация прошла успешно. Теперь вы можете работать с сайтом как администратор.</div> <br><hr><br><div class='goto_admin_icon'><a href='index.cfm?adm=main'>Перейти в систему администрирования</a></div><div class='goto_arxiv_icon'><a href='index.cfm?mod=filearch2_cats_list'>Перейти в файловый архив</a></div><div class='goto_site_icon'><a href='index.cfm'>Перейти на сайт</a></div><br><br>";
  $l_auth[9]  = "<p>Здравствуйте, <b>{name}</b>, авторизация прошла успешно.<p/> <br><hr><br><center><a href='index.cfm'>Перейти на сайт</a></center><br><br>";
  $l_auth[10] = "<div class='user_icon'>Здравствуйте, <b>{name}</b>, авторизация прошла успешно. Теперь вы можете работать с сайтом как редактор.</div> <br><hr><br><div class='goto_arxiv_icon'><a href='index.cfm?mod=filearch2_cats_list'>Перейти в файловый архив</a></div><div class='goto_site_icon'><a href='index.cfm'>Перейти на сайт</a></div><br><br>";
//auth_form_on_page
  //h1
  $l_auth[11] = "Войти";
//bbd_auth.cfm
  $l_auth[12] = "";

//auth_form.inc
  $l_auth[13] = "Забыли пароль";
?>