<?php
//blocks_list.inc
  //h1
  $l_blockeditor[1] = "блоки текста";
  //caption
  $l_blockeditor[2] = "Тип блока";
  //$l_blockeditor[3] = "caption";
  //option
  $l_blockeditor[4] = "Текстовый блок";
  $l_blockeditor[5] = "Список";
  $l_blockeditor[6] = "Серию изображений";
  $l_blockeditor[7] = "Файл";
  $l_blockeditor[8] = "Таблица";
  //button
  $l_blockeditor[9] = "Добавить";
  //th
  $l_blockeditor[10] = "поз.";
  $l_blockeditor[11] = "тип блока";
  $l_blockeditor[12] = "содержание";
  $l_blockeditor[13] = "опции";
  //captions blocks types
  $l_blockeditor[14] = "заголовок 1";
  $l_blockeditor[15] = "заголовок 2";
  $l_blockeditor[16] = "заголовок 3";
  $l_blockeditor[17] = "текст, выравнивание по ширине";
  $l_blockeditor[18] = "текст, выравнивание по левому краю";
  $l_blockeditor[19] = "текст, выравнивание по центру";
  $l_blockeditor[20] = "текст, выравнивание по правому краю";
  $l_blockeditor[21] = "маркированный список";
  $l_blockeditor[22] = "буквенный список";
  $l_blockeditor[23] = "цифровой список";
  $l_blockeditor[24] = "изображения";
  $l_blockeditor[25] = "файл";
  $l_blockeditor[26] = "картинки с описанием, текст справа";
  $l_blockeditor[27] = "картинки с описанием, текст снизу";
  //options
  $l_blockeditor[28] = "изменить";
  $l_blockeditor[29] = "изображения";
  $l_blockeditor[30] = "удалить";
  //info
  $l_blockeditor[31] = "Данная страница не содержит блоков.";
//_block_edit
  $l_blockeditor[32] = "картинки без пояснительного текста";
  $l_blockeditor[33] = "картинки с текстом справа";
  $l_blockeditor[34] = "картинки с текстом снизу";
  $l_blockeditor[35] = "Текст";
  $l_blockeditor[36] = "Позиция";
  $l_blockeditor[37] = "Файл";
  $l_blockeditor[38] = "Название";
  $l_blockeditor[39] = "Тип текстового блока";
  $l_blockeditor[40] = "Заменить перевод<br>строки на &lt;br&gt;";
  $l_blockeditor[41] = "Пункты (разделяются клавишей Enter)";
  $l_blockeditor[42] = "Тип списка";
  $l_blockeditor[43] = "Заменить перевод строки на &lt;br&gt;";
  $l_blockeditor[44] = "Кол-во изображений в одном ряду";
  $l_blockeditor[45] = "Тип блока";
//blocks_add.inc, blocks_edit.inc
  $l_blockeditor[46] = "Введите, пожалуйста, целое положительное число в поле <b>позиция</b>.";
  $l_blockeditor[47] = "Введите, пожалуйста, текст.";
  $l_blockeditor[48] = "Вы забыли загрузить файл.";
  $l_blockeditor[49] = "Параметры блока";
  $l_blockeditor[50] = "Добавить блок";
//blocks_del.inc
  $l_blockeditor[51] = "Хотите удалить этот блок?";
//images_list.inc
  $l_blockeditor[52] = "изображения";
  $l_blockeditor[53] = "Добавить изображение";
  $l_blockeditor[54] = "позиция";
  $l_blockeditor[55] = "название";
  $l_blockeditor[56] = "картинка";
  $l_blockeditor[57] = "опции";
  $l_blockeditor[58] = "параметры";
  $l_blockeditor[59] = "удалить";
  $l_blockeditor[60] = "Не добавлено ни одного изображения.";
//_images_edit.inc
  $l_blockeditor[61] = "Название";
  $l_blockeditor[62] = "Уменьшенная копия изображения";
  $l_blockeditor[63] = "Увеличенная копия изображения";
  $l_blockeditor[64] = "Позиция";
  $l_blockeditor[65] = "Пояснительный текст";
//images_edit. add.inc
  //h1
  $l_blockeditor[66] = "Добавить изображение";
  $l_blockeditor[67] = "Параметры изображения";
  //errors
  $l_blockeditor[68] = "Введите целое положительное число в поле <b>позиция</b>.";
  $l_blockeditor[69] = "Вы забыли загрузить изображение (уменьшенную копию).";
//images_del.inc
  $l_blockeditor[70] = "Хотите удалить это изображение?";
  $l_blockeditor[71] = "Вернуться в список блоков";


//_block_edit.inc
  $l_blockeditor[72] = "Название (подстановка [size] заменяется на размер файла в килобайтах)";


//blocks_list.inc
  //caption
  $l_blockeditor[73] = "новая страница";
  //form select option
  $l_blockeditor[74] = "Новая страница";
  //caption
  $l_blockeditor[75] = "С отмеченными";
  //buttons
  $l_blockeditor[76] = "Удалить";
  $l_blockeditor[77] = "Переместить";

//blocks_del_all.inc
  $l_blockeditor[78] = "Хотите удалить этих пользователей?";
  $l_blockeditor[79] = "Предупреждение";
  $l_blockeditor[80] = "Не выбрано ни одного блока.";
  $l_blockeditor[81] = "Выберите позицию первого элемента";
  $l_blockeditor[82] = "Переместить группу блоков";
  $l_blockeditor[83] = "";
?>