    <ul class="breadcrumbs">
      <li><a href="index.cfm">Главная</a></li>
      <li class="current"><a href="#">Политика авторского права в Интернете</a></li>
    </ul>
   	<h2>Политика авторского права в Интернете</h2>
<!--  -->           	

<p>Основополагающая политика "Коллектора библейской книги", касающаяся распространения в Интернете любых защищённых авторским правом материалов "Коллектора библейской книги", проста: все электронные материалы "Коллектора библейской книги" публикуются только на официальных сайтах "Коллектора библейской книги". При этом мы приветствуем ссылки на наши сайты и ссылки на отдельные страницы наших сайтов.</p>

<p>Значительная часть наших публикаций доступна для чтения в Интернете по адресу <strong><a href="http://www.ministrybooks.ru">www.ministrybooks.ru</a></strong>. По мере наших возможностей мы периодически добавляем на этот сайт новые публикации и считаем, что это исключает необходимость размещения кем-либо этих материалов на других Интернет-ресурсах. Если наш сайт не соответствует каким-либо конкретным потребностям, сообщите нам об этом по адресу <strong><a href="mailto:books@kbk.ru">books@kbk.ru</a></strong>. Мы рассмотрим вашу просьбу с учётом других подобных запросов и имеющихся у нас возможностей.</p>

<p>Любой человек может цитировать в Интернете опубликованные законным способом материалы "Коллектора библейской книги" в объёме, оправданном целью цитирования, как указано в статье 1274 Гражданского кодекса РФ. Такое цитирование считается "добросовестным использованием" материалов согласно требованиям закона США о защите авторских прав в сфере цифровой информации в новом тысячелетии (DMCA).</p>

<p><strong>Что касается использования материалов "Коллектора библейской книги", мы толкуем "добросовестное использование" следующим образом:</strong></p>

<ol>
<li><p>Ни на каком Интернет-ресурсе не может быть размещена большая часть полной текстовой публикации (более 50%). Полной публикацией считается глава книги, статья, брошюра, печатное сообщение и т. п.</p></li>
<li><p>Полной публикацией также считается любая веб-страница какого-либо официального сайта "Коллектора библейской книги". Цитата не должна содержать более 50% цитируемой веб-страницы.</p></li>
<li><p>Любую цитату из публикаций "Коллектора библейской книги" следует приводить надлежащим образом, без ошибок, с указанием автора, названия произведения, издателя, а также точных номеров страниц или адреса страницы в Интернете (URL), с которой взята цитата. Мы понимаем, что для этого потребуются определённые усилия, но это соответствует давно установленным и общепризнанным нормам цитирования.</p></li>
</ol>
<p>Мы не разрешаем скачивания какого-либо издания "Коллектора библейской книги" в электронном формате, за исключением случаев, когда наше издание приобретено в "Коллекторе библейской книги" на сайте <strong><a href="http://kbk.ru">www.kbk.ru</a></strong> для личного использования.
</p>
<p>Не разрешается распространение изданий "Коллектора библейской книги" в печатном или электронном виде за исключением случаев, в которых "Коллектор библейской книги" в письменной форме уполномочил какое-либо лицо для распространения своих изданий. Это касается также изданий, приобретённых для личного использования, в том числе преобразованных для использования на других программных платформах.</p>

<!-- 
   	<h2>Internet Copyright Policy</h2>
           	
    <p>The following is our copyright policy concerning the use of any Living Stream Ministry materials on the Internet.</p>
		<p>Living Stream Ministry's fundamental policy on making LSM-copyrighted content available on the Internet is simple:</p>
		<p>All electronic LSM materials should reside on an LSM site. However, links to LSM sites and particular LSM web pages are greatly encouraged.</p>
		<p>We currently make the bulk of our publications available online at <a href="http://www.ministrybooks.org">www.ministrybooks.org</a>, and we are constantly adding more titles as time and resources allow. In nearly all cases, this precludes the need for others to post LSM content on their own sites. If our website <a href="http://www.ministrybooks.org">www.ministrybooks.org</a> does not suit the particular needs of an individual, church, or organization, please contact us at <a href="mailto:webmaster@lsm.org">webmaster@lsm.org</a>. We will consider your request in light of other similar requests and based upon our available resources.</p>
		<p>Nevertheless, we acknowledge that anyone may include scattered quotations of copyrighted materials on his or her web site as long as such quotation would be considered "fair use" according to the U.S Copyright Act. As it concerns the use of LSM materials, we interpret fair use as follows:</p>
		<ol>
      <li><span>No website may publish a majority (more than 50%) of any complete work. A complete work is defined as any complete published entity. For example, any whole tract, booklet, chapter of a book, book, hymn, article, etc. would be considered a complete published entity.</span></li>
      <li><span>Quoted LSM material may not constitute a majority of any page's content (i.e., more than 50% of any one Web page).</span></li>
      <li><span>Any quotation taken from LSM publications should be given a proper citation, including the author's name, the title of the work, the title of the source, the publisher, the place and date of publication, and the exact page number(s) or URL from which the quotation was taken. We realize that this can be a laborious task, but it is in keeping with the long-established norms for attributing quoted material to its proper source.</span></li>
    </ol>
    <p>Finally, we do not allow the downloading of any LSM publication in electronic format, except when purchased from an authorized distributor or specifically authorized in writing by Living Stream Ministry. Furthermore, we do not allow the distribution of an LSM publication in electronic format except for those authorized by LSM to do so. This includes any purchased publication that has been converted for use on other platforms such as PDAs, etc. Downloading for so-called "personal use" is also prohibited.</p>      
-->
<div class='to-top'><a href='#top' class='scroll'>В начало</a></div>