<ul class='breadcrumbs'>
      <li><a href='index.cfm'>Главая</a></li>
      <li class='current'><a href='?mod=life_study'>Сайты «Коллектора библейской книги»</a></li>
    </ul>
<h2>Сайты «Коллектора библейской книги»</h2>
<dl>  	
<dt>
	<a href="http://kbk.ru/" target="_blank">Интернет-магазин издательства «Коллектор библейской книги»  — www.kbk.ru</a></dt>
<dd>На сайте можно приобрести печатные и электронные издания, аудио и видео материалы служения братьев Вочмана Ни и Уитнесса Ли.</dd>
<dt>
	<a href="http://www.watchmannee.ru/" target="_blank">Вочман Ни  — www.watchmannee.ru</a><br><a href="http://www.witnesslee.ru/" target="_blank">Уитнесс Ли  — www.witnesslee.ru</a>
</dt>
    <dd>Сайты о жизни и служении двух известных христианских авторов XX века. Свидетельства, учение и обзор трудов.</dd>
<dt><a href="http://recoveryversion.ru/" target="_blank">Новый завет Восстановительный перевод Онлайн — www.recoveryversion.ru</a></dt>
<dd>Читайте Восстановительный перевод Нового Завета онлайн с примечаниями, перекрёстными ссылками, возможностью поиска и т.п.</dd>

<dt><a href="http://www.rhemabooks.org/rus/Home" target="_blank"><strong>Миссия «Рема» — www.rhemabooks.org</strong></a></dt>
<dd>Миссия "Рема" распространяет бесплатную христианскую литературу более чем на 25 языках. «Рема» предлагает на заказ богатую коллекцию лучшей христианской литературы, которая помогает верующим субъективно познавать Христа в их повседневной жизни.</dd>

<dt><a href="http://bibleforall.ru/" target="_blank"><strong>Библия, открытая для всех — www.bibleforall.ru</strong></a></dt>
<dd>На этом сайте миссии «Рема» вы можете заказать бесплатный экземпляр Восстановительного перевода Нового Завета с доставкой по почте. Заказы доступны из России, Украины, Белоруссии, Латвии, Эстонии и США.</dd>
<dt><a href="http://www.emanna.com/russian/index.html" target="_blank"><strong>eManna (электронная манна) — www.emanna.com</strong></a></dt>
<dd>eManna доставляет Слово Божье как хлеб жизни каждый день по электронной почте. Письмо включает в себя несколько стихов из Библии и небольшой отрывок из служения для питания и укрепления вашей веры. Рассылка бесплатная.</dd>
<dt><a href="http://forfaith.ru/" target="_blank"><strong>«Защищая веру» — www.forfaith.ru</strong></a></dt>
<dd>Этот сайт посвящён вопросам и спорам, которые иногда возникают в отношении служения Вочмана Ни, Уитнесса Ли и поместных церквей. Он содержит материалы, представляющие служение Вочмана Ни и Уитнесса Ли в истинном свете.</dd>		
		<hr>
		<h3>Сайты на английском языке</h3>
<dt><a href="http://www.lsm.org/" target="_blank"><strong>Living Stream Ministry — www.lsm.org</strong></a></dt>
<dd>Living Stream Ministry is a non-profit corporation that is primarily dedicated to the publication of the ministry of Watchman Nee and Witness Lee. Living Stream Ministry has one goal: to supply spiritual food for the nourishment of all believers that they may grow in the divine life for the sake of the building up of the Body of Christ.</dd>
<dt>
			<a href="https://www.livingstream.com/" target="_blank"><strong>Online Bookstore — www.livingstream.com</strong></a></dt>
<dd>
Living Stream Ministry publishes the works of Watchman Nee and Witness Lee, providing the authoritative and definitive collections of treasures from these two servants of the Lord Jesus Christ. Their writings focus on the enjoyment of the divine life, which all the believers possess, and on the building up of the church, the goal of God's work with man in this age.</dd>

<dt><a href="http://www.recoveryversion.org/" target="_blank"><strong>The Recovery Version of the Bible — www.recoveryversion.org</strong></a></dt>
<dd>
The Recovery Version of the Bible contains numerous study aids, including, the subject and background of each book; detailed, interpretive outlines; enlightening footnotes, valuable cross-references, and a variety of useful charts and maps.
		</dd>
	<dl> 
<div class='to-top'><a href='#top' class='scroll'>В начало</a></div>